media:
  input: public/cdn-media
  output: /cdn-media
content:
  - name: sections
    label: 📑 Sections
    type: collection
    path: "src/cdn/sections"
    view:
      fields: [title, published]
    fields:
      - name: published
        label: Published
        type: boolean
        default: false
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: site
    label: ⚙️ Site Settings
    path: src/cdn/site.json
    type: file
    fields:
      - name: siteTitle
        label: Site Title
        type: string
      - name: siteDescription
        label: Site Description
        type: string
  - name: user
    label: 🤠 User Information
    path: src/cdn/user.json
    type: file
    fields:
      - name: userName
        label: Full Name
        type: string
      - name: userEmail
        label: Email
        type: string
      - name: userSocials
        label: Socials
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
          - name: url
            label: URL
            type: string
